"""add source episode id

Revision ID: 06975e592175
Revises: 3fe865f8f737
Create Date: 2026-09-04 18:25:25.568844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06975e592175'
down_revision: Union[str, Sequence[str], None] = '3fe865f8f737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('source_episode_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'episodes', ['source_episode_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'episodes', type_='unique')
    op.drop_column('episodes', 'source_episode_id')
    # ### end Alembic commands ###
